import { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAdmin } from '../context/AdminContext';
import { Lock, Loader2, Shield, ArrowRight } from 'lucide-react';
import clsx from 'clsx';

const TwoFactor = () => {
    const [code, setCode] = useState(['', '', '', '', '', '']);
    const inputs = useRef([]);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState('');
    const { verify2FA } = useAdmin();
    const navigate = useNavigate();
    const [shake, setShake] = useState(false);
    const [timeLeft, setTimeLeft] = useState(59);

    useEffect(() => {
        const timer = setInterval(() => {
            setTimeLeft((prev) => (prev > 0 ? prev - 1 : 0));
        }, 1000);
        return () => clearInterval(timer);
    }, []);

    const handleChange = (index, value) => {
        if (!/^\d*$/.test(value)) return;

        const newCode = [...code];
        newCode[index] = value;
        setCode(newCode);

        // Auto-advance
        if (value && index < 5) {
            inputs.current[index + 1].focus();
        }
    };

    const handleKeyDown = (index, e) => {
        if (e.key === 'Backspace' && !code[index] && index > 0) {
            inputs.current[index - 1].focus();
        }
    };

    const handlePaste = (e) => {
        e.preventDefault();
        const pastedData = e.clipboardData.getData('text').slice(0, 6);
        if (!/^\d+$/.test(pastedData)) return;

        const newCode = [...code];
        pastedData.split('').forEach((char, index) => {
            if (index < 6) newCode[index] = char;
        });
        setCode(newCode);
        inputs.current[Math.min(pastedData.length - 1, 5)].focus();
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        const fullCode = code.join('');
        if (fullCode.length !== 6) return;

        setIsLoading(true);
        setError('');

        try {
            await verify2FA(fullCode);
            navigate('/verify-device');
        } catch (err) {
            setError(err);
            setIsLoading(false);
            setShake(true);
            setTimeout(() => setShake(false), 500);
        }
    };

    return (
        <div className="min-h-screen bg-black text-foreground flex items-center justify-center relative overflow-hidden font-sans">
            {/* Background Effects */}
            <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 pointer-events-none"></div>
            <div className="absolute inset-0 bg-gradient-to-b from-black via-transparent to-black pointer-events-none"></div>

            <div className={clsx(
                "relative z-10 w-full max-w-md p-8 rounded-2xl border border-white/10 bg-black/40 backdrop-blur-xl shadow-2xl transition-transform duration-300",
                shake ? "animate-shake" : ""
            )}>
                <div className="text-center mb-8">
                    <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-white/5 border border-white/10 mb-4">
                        <Shield className="w-5 h-5 text-white" />
                    </div>
                    <h1 className="text-2xl font-bold tracking-tight text-white mb-2">Two-Factor Auth</h1>
                    <p className="text-sm text-neutral-400">Enter the 6-digit verification code generated by your device.</p>
                </div>

                <form onSubmit={handleSubmit} className="space-y-8">
                    <div className="flex justify-between gap-2" onPaste={handlePaste}>
                        {code.map((digit, index) => (
                            <input
                                key={index}
                                ref={(el) => (inputs.current[index] = el)}
                                type="text"
                                maxLength={1}
                                value={digit}
                                onChange={(e) => handleChange(index, e.target.value)}
                                onKeyDown={(e) => handleKeyDown(index, e)}
                                className="w-12 h-12 bg-black/50 border border-white/10 rounded-lg text-center text-xl font-bold text-white focus:border-white/50 focus:ring-1 focus:ring-white/50 focus:outline-none transition-all"
                            />
                        ))}
                    </div>

                    {error && (
                        <p className="text-red-400 text-sm text-center bg-red-400/10 border border-red-400/20 py-2 rounded-lg animate-fade-in-up">{error}</p>
                    )}

                    <div className="text-center">
                        <button
                            type="submit"
                            disabled={isLoading || code.join('').length !== 6}
                            className="w-full bg-white text-black font-semibold py-3 rounded-lg hover:bg-neutral-200 focus:outline-none focus:ring-2 focus:ring-white/50 focus:ring-offset-2 focus:ring-offset-black transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
                        >
                            {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : 'Verify Code'}
                        </button>
                    </div>

                    <div className="flex items-center justify-between text-xs text-neutral-500">
                        <div className="flex items-center space-x-1">
                            <Lock className="w-3 h-3" />
                            <span>Code expires in 00:{timeLeft.toString().padStart(2, '0')}</span>
                        </div>
                        <button type="button" className="hover:text-white transition-colors">Resend code</button>
                    </div>
                </form>
            </div>
            {/* Styles for shake animation */}
            <style>{`
                @keyframes shake {
                    0%, 100% { transform: translateX(0); }
                    10%, 30%, 50%, 70%, 90% { transform: translateX(-4px); }
                    20%, 40%, 60%, 80% { transform: translateX(4px); }
                }
                .animate-shake {
                    animation: shake 0.4s cubic-bezier(.36,.07,.19,.97) both;
                }
                 @keyframes fade-in-up {
                    from { opacity: 0; transform: translateY(10px); }
                    to { opacity: 1; transform: translateY(0); }
                }
                .animate-fade-in-up {
                    animation: fade-in-up 0.3s ease-out forwards;
                }
            `}</style>
        </div>
    );
};

export default TwoFactor;
